/* Automatically generated by './build/bin/build-entry.js' */


// 导入基于element二次开发的组件
import EL2Dialog from '../packages/dialog';


const components = [
  // element二次封装组件
  EL2Dialog,
];

const install = function (Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.0.1',
  install,
  EL2Dialog,
};
