/* Automatically generated by './build/bin/build-entry.js' */


// 导入基于vant二次开发的组件
import Van2Address from '../packages/address';
import Van2Ruler from '../packages/ruler';

const components = [
  // vant二次封装组件
  Van2Address,
  Van2Ruler
];

const install = function (Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.0.1',
  install,
  Van2Address,
  Van2Ruler
};
