/* Automatically generated by './build/bin/build-entry.js' */

// 导入自定义组件
import Video from '../packages/component/video';
import Svg from '../packages/component/svg';
import Button from '../packages/component/button';
import Tabs from '../packages/component/tabs'
import TabPane from '../packages/component/tab-pane'

// 导入基于element二次开发的组件
import EL2Dialog from '../packages/element/dialog';

// 导入基于vant二次开发的组件
import Van2Address from '../packages/vant/address';

const components = [
  Svg,
  Video,
  Button,
  TabPane,
  Tabs,
  // element二次封装组件
  EL2Dialog,
  // vant二次封装组件
  Van2Address
];

const install = function (Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.0.1',
  install,
  Svg,
  Video,
  Button,
  Tabs,
  TabPane,
  EL2Dialog,
  Van2Address,
};
