/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button';
// 导入组件
import Tabs from '../packages/tabs'
import TabPane from '../packages/tab-pane'

const components = [
  Button,
  TabPane,
  Tabs,
];

const install = function (Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.0.1',
  install,
  Button,
  Tabs,
  TabPane,
};
